
name: Deploy Java project to Azure Function App

on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: espd-designer-backend-win(stage)   # set this to your function app name on Azure
  POM_XML_DIRECTORY: '.'                     # set this to the directory which contains pom.xml file
  POM_FUNCTIONAPP_NAME: espd-designer-backend-win(stage)        # set this to the function app name in your local development environment
  JAVA_VERSION: '11'                      # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: "Run install of deps"
        shell: bash
        run: |
          git clone --branch gsccp-develop http://stash.ds.unipi.gr/scm/espd/espd-vcd-system.git 
          cd espd-vcd-system
          ./gradlew install

      - name: 'Checkout Master'
        uses: actions/checkout@master

      - name: 'Restore Project Dependencies Using Gradle'
        shell: bash
        run: |
          ./gradlew clean azureFunctionsPackage
          

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './${{ env.POM_XML_DIRECTORY }}/build/azure-functions/${{ env.POM_FUNCTIONAPP_NAME }}'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
